#Introduction to Numpy :


In [123]:
import numpy as np

In [124]:
my_list = [0,1,2,3,4]

In [125]:
my_list

[0, 1, 2, 3, 4]

In [126]:
ar = np.array(my_list)

In [127]:
ar

array([0, 1, 2, 3, 4])

**Arange**

In [128]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [129]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

**array of zeros, ones and any other number**

In [130]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [131]:
np.zeros((3,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [132]:
np.zeros((5,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [133]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [134]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [135]:
azz = np.full((2,2), 90)
azz

array([[90, 90],
       [90, 90]])

In [136]:
np.full_like(azz , 6)

array([[6, 6],
       [6, 6]])

**filling an array with randoms**

In [137]:
np.random.rand(2,3,4)

array([[[0.31552421, 0.90653395, 0.00137097, 0.57548998],
        [0.47452438, 0.27205127, 0.26839872, 0.98711439],
        [0.92971622, 0.18492277, 0.453444  , 0.44734283]],

       [[0.2529741 , 0.87419676, 0.28886169, 0.31945995],
        [0.57593824, 0.80803649, 0.24148478, 0.83491168],
        [0.74713195, 0.44130989, 0.0890517 , 0.38334925]]])

In [138]:
np.random.randint(0,8)

2

In [139]:
np.random.randint(0,10,(4,4))
#np.random.randint(0,10,size=(4,4))

array([[3, 2, 6, 9],
       [4, 6, 4, 8],
       [6, 2, 3, 1],
       [5, 2, 1, 8]])

In [140]:
var = np.linspace(0,10,5)
var

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [141]:
type(var)

numpy.ndarray

In [142]:
var

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [143]:
np.random.seed(20)
var1 = np.random.randint(1,10,5)

In [144]:
var1

array([4, 5, 7, 8, 3])

In [145]:
arr = np.random.randint(0,100,10)
arr

array([96, 40, 85, 90, 26, 83, 16, 62, 16,  7])

**max/min value and max/min arguments**

In [146]:
np.max(arr)

96

In [147]:
arr.argmax()

0

In [148]:
arr.min()

7

In [149]:
arr.argmin()

9

In [150]:
arr.mean()

52.1

In [191]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [193]:
np.max(stats , axis=1)

array([3, 6])

**reorganazing arrays**

In [199]:
before = np.array([1,2,3,4,5,6,7,8,9,10])
before

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [200]:
before.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [202]:
mat = np.arange(0,100,1).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [208]:
c = np.array([1,2,3])
d = np.array([4,5,6])
np.vstack([c,d, c , d])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [209]:
np.hstack((d,c))

array([4, 5, 6, 1, 2, 3])

**Slicing and replacing**

In [212]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [210]:
row = 1
col = 1
mat[row , col]

11

In [211]:
mat[:, col]

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [156]:
mat[0:3, col]

array([ 1, 11, 21])

In [157]:
mat[row , :]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [214]:
mat[[1,2,8]]      # indexing with a list

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89]])

In [215]:
np.any(mat>50)

True

In [218]:
np.all(mat < 50 )

False

In [158]:
mat > 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [159]:
mat[mat>50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [160]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
arr[1, 1:4]

array([7, 8, 9])

In [161]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

arr[0:2, 2]

array([3, 8])

In [162]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
arr[0:2, 1:4]

array([[2, 3, 4],
       [7, 8, 9]])

In [163]:
#[start:end:step]
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


In [164]:
aaaa= np.array([[1,2,3,4],[5,6,7,8]])
print(aaaa)

[[1 2 3 4]
 [5 6 7 8]]


In [165]:
print(aaaa[1, 2:4])

[7 8]


In [166]:
aaaa[1,2]

7

In [167]:
aaaa[1,2]=12
aaaa

array([[ 1,  2,  3,  4],
       [ 5,  6, 12,  8]])

In [168]:
aaaa[:,2]=aaaa[1,2]
aaaa

array([[ 1,  2, 12,  4],
       [ 5,  6, 12,  8]])

In [169]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
b[0,1,1]

4

**dimensions**

In [170]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [171]:
arr.ndim

2

In [172]:
arr = np.array([1, 2, 3, 4], ndmin=5)
arr

array([[[[[1, 2, 3, 4]]]]])

**data type and array type**

In [173]:
arr = np.array([1, 2, 3, 4])
arr.dtype     #datatype


dtype('int64')

In [174]:
type(arr)    #arraytype

numpy.ndarray

**Be careful when copying arrays!!**

In [175]:
a = np.array([1,2,3])
b=a
b
b[0]=100
a
#cause a and b are pointing to the same array

array([100,   2,   3])

In [176]:
aa = np.array([1,2,3])
bb = aa.copy()              ## copy here pevents that
bb[0]=100
aa

array([1, 2, 3])

**Mathematics**

In [177]:
ar1 = np.array([1,2,3,4])
ar1-2

array([-1,  0,  1,  2])

In [178]:
ar1+2

array([3, 4, 5, 6])

In [179]:
ar1*2

array([2, 4, 6, 8])

In [180]:
ar1/2

array([0.5, 1. , 1.5, 2. ])

In [181]:
ar1**2

array([ 1,  4,  9, 16])

In [182]:
np.cos(ar1)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [183]:
ar2 = np.array([1,0,1,0])
ar1+ar2

array([2, 2, 4, 4])

**Linear Algebra**

In [184]:
a1 = np.ones((2,3))
a1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [185]:
b1 = np.full((3,2), 2)
b1

array([[2, 2],
       [2, 2],
       [2, 2]])

In [186]:
np.matmul(a1,b1)

array([[6., 6.],
       [6., 6.]])

In [187]:
c = np.identity(3)
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [188]:
np.linalg.det(c)

1.0

**Load data from text**

In [188]:
#filedata = np.genfromtxt('data.txt' , delimiter=',')
#filedata.astype('int32')
#filedata